config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :contacts, controller: 'users/contacts' do
      resources :phones, only: [:index, :create, :new, :destroy]
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # => Diz que contato faz parte de "user"
  belongs_to :user

  # => dependent: :destroy -> Quando apagar, apagar os também os "phones"
  # => dependent: :restrict -> Não permite apagar caso tenha "phones"
  # => :dependent => :destroy é igual a dependent: :destroy
  has_many :phones, dependent: :destroy

  # => Libera o model para poder trabalhar com "phones"
  accepts_nested_attributes_for :phones,
    reject_if: lambda { |a| a[:number].blank?}, # => Rejeitar caso o número vier em branco
    allow_destroy: true # => Deixa apagar o registro do model "phone" através no model Contact
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  # Callback
  before_save do
    if self.default
        contact.phones.each do |phone|
            phone.update! default: false
        end
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
    # Colocar relacionamentos antes das validações
    has_many :contacts

    validates_presence_of :name
    validates_uniqueness_of :name
    validates_numericality_of :age, greater_than: 0, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :set_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = @user.contacts.includes(:phones).all # => deixa os phones carregados no objeto
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new

    # Reserva 4 espaços para armazenar os telefones
    4.times { @contact.phones.build }
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = @user.contacts.new(contact_params)
    @contact.user_id = params[:user_id]

    respond_to do |format|
      if @contact.save
        format.html { redirect_to user_contact_path(@contact.user_id, @contact), notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to user_contact_path(@contact.user_id, @contact), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to user_contacts_url(@contact.user_id), notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
      format.js # => Responde ajax
    end
  end

  private

    def set_user
      @user = User.find(params[:user_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phones, :born_date, phones_attributes: [:name, :number, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user.id)
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to(name, "javascript:void(0)", onclick: "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, "javascript:void(0)", onclick: h("add_fields(this, \"#{association}\",\"#{escape_javascript(fields)}\")"))
  end
end

app/helpers/users/contacts_helper.rb
module Users::ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/contacts/_form.html.erb
<%= form_for ([@user, @contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="fields">

  <%= f.text_field :name %><br />
  <%= f.date_field :born_date %><br />

  <%= f.fields_for :phones do |builder| %>
   <%= render "phone_fields", f: builder %>
  <% end %>

  <p><%= link_to_add_fields "Add Phone", f, :phones %></p>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/contacts/_phone_fields.html.erb
<!-- Formulário para os campos de telefones -->
<p class="fields">
  <%= f.label :number, "Number" %>
  <%= f.text_field :number %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/users/contacts/destroy.js.erb
$("#contact_<%= @contact.id %>").remove();

app/views/users/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', user_contact_path(@contact.user_id, @contact) %> |
<%= link_to 'Back', user_contacts_path(@contact.user_id) %>

app/views/users/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr id="contact_<%= contact.id %>">
        <td><%= contact.name %></td>
        <td><% contact.phones.each do |phone| %>
          <tr id="phone_<%= phone.id %>">
            <td>
              <%= phone.number %>
            </td>
          </tr>
        </td>
        <% end %>
        <td><%= link_to 'Show', user_contact_path(contact.user_id, contact) %></td>
        <td><%= link_to 'Edit', edit_user_contact_path(contact.user_id, contact) %></td>
        <td><%= link_to 'Destroy', user_contact_path(contact.user_id, contact), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_user_contact_path %>

app/views/users/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', user_contacts_path %>

app/views/users/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_contact_path(@contact.user_id, @contact) %> |
<%= link_to 'Back', user_contacts_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.name %></p>
  <p><%= link_to 'Acessar', user_path(user.id) %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h2><%= @user.age  %></h2>
<h2><%= @user.bio  %></h2>
<h2><%= @user.contacts.count  %></h2>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>